; $Id: //depot/external/ia32_bits.inc#1 $

;------------------------------------------------------------------------------
;	prevent multiple inclusions of this file
;------------------------------------------------------------------------------

%ifndef INCLUDED_IA32_BITS

%define 		INCLUDED_IA32_BITS	BOOL_TRUE

;------------------------------------------------------------------------------
;	address bits
;------------------------------------------------------------------------------

%define			BITS_IA32_PHYSICAL	36
%define			BITS_IA32_VIRTUAL	32

;------------------------------------------------------------------------------
;	end of file
;------------------------------------------------------------------------------

%endif

;------------------------------------------------------------------------------
;
;  *************************************************************************
;  *                                                                       *
;  * This software is provided "as is", and any warranties are disclaimed. *
;  * In no event shall the copyright holder(s), author(s), contributor(s), *
;  * or distributor(s) be liable for any damages arising in any way out of *
;  * the use of this software.                                             *
;  *                                                                       *
;  *************************************************************************
;
;EOF
